### ISSUE TITLE
How did you get this information

### ISSUE THREAD

**Issue by jelluh24** [modux/Nintendo-Switch-Forensics#1]
Hey, 
I was wondering where you got the file locations and information from. Did you find it yourself or is there some documentation of where everything is stored? Right now the only way for me to find where certain information is stored is by looking at your scripts (and switchbrew.org, but that doesn't seem extremely useful.)
Thank you!

**Comment by secdefect** [comment]
Hi. One of our teams spent 3 months working on the Nintendo switch and performing manual analysis of the filesystem and file structures.

We hope you find it useful. Sorry for the late reply.
