### ISSUE TITLE
Future Artifacts

### ISSUE THREAD

**Issue by upintheairsheep** [modux/Nintendo-Switch-Forensics#2]
1. Nintendo Switch’s Hidden Browser
2. Accounts
3. Bluetooth devices paired
4. YouTube app token
5. Netflix app token
6. “Notes” game phrasing

**Comment by b-mdx** [comment]
Development on this project has paused.

We welcome any pull requests however if you wanted to implement any of the additional artefacts yourself.

Many thanks,
Ben
